%% SEIR Model Parameters

% after the global statement, list all of your parameters.
global  rho ...
        betaONE ...
        betaTWO ... 
        mu ...
        alpha ...
        gamma ...
        proportion ...
        epsilon ...
        eta ...
        theta ...
        lambda ...
       

rho = 0.043; %/12;
betaONE = 0.7;
betaTWO = betaONE;
mu = .016;
alpha = 16.4;%/12;
gamma = 1/3;            %1/9 - 1/3  ;
proportion = .095;
epsilon = 1/100;         %1/24 - 0
eta = 1/3;             %1/60-1/3
theta = 1/3;           %1/6 - 1/0.5
lambda =  1/50;           %1/20 - 1/2


    